version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-adonis
    restart: always
    environment:
      POSTGRES_USER: adonis
      POSTGRES_PASSWORD: adonis
      POSTGRES_DB: adonisdb
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: